name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      run: docker build -t wisecow .

    - name: Tag Docker image
      run: docker tag wisecow:latest rahulrajak/wisecow:latest

    - name: Push Docker image to Docker Hub
      run: docker push rahulrajak/wisecow:latest

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --name project11 --region ${{ secrets.AWS_REGION }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: '1.25.0' # Specify the Kubernetes CLI version you need

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f wisecow-deployment.yml
        kubectl apply -f wisecow-service.yml
        kubectl apply -f wisecow-ingress.yaml
        kubectl rollout status deployment/wisecow-deployment
